name: ht_preferences_repository
description: Repository for managing user preferences. This repository acts as an intermediary between the application's business logic (BLoCs) and the data source client (`HtPreferencesClient`). It handles potential client-level exceptions and enforces additional business rules, such as limiting the size of the headline reading history.
repository: https://github.com/headlines-toolkit/ht-preferences-repository
publish_to: none

environment:
  sdk: ^3.7.0

dependencies: 
  ht_preferences_client:
    git:
        url: https://github.com/headlines-toolkit/ht-preferences-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
